### ISSUE TITLE
Multiprocessing bug

### ISSUE THREAD

**Issue by SamAllon** [faircloth-lab/edittag#4]
Thanks for writing this tool -I've found it helpful. As I try to design very large tag sets, it would be great to use the multiprocessing feature. However, including the --multiprocessing flag results in a bug during the Processing... step after [4] Calculating the Levenshtein distance across the tags.

Specifically:

[4] Calculating the Levenshtein distance across the tags
	[Info] There are 9 chunks.
	Processing: .........Traceback (most recent call last):
  File "/Users/allons/anaconda3/envs/zipcode/bin/design_edit_metric_tags.py", line 4, in <module>
    __import__('pkg_resources').run_script('edittag==1.1', 'design_edit_metric_tags.py')
  File "/Users/allons/anaconda3/envs/zipcode/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/allons/anaconda3/envs/zipcode/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/Users/allons/anaconda3/envs/zipcode/lib/python2.7/site-packages/edittag-1.1-py2.7.egg/EGG-INFO/scripts/design_edit_metric_tags.py", line 500, in <module>
    
  File "/Users/allons/anaconda3/envs/zipcode/lib/python2.7/site-packages/edittag-1.1-py2.7.egg/EGG-INFO/scripts/design_edit_metric_tags.py", line 457, in main
    
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by bwlang** [comment]
I have just observed the same issue:
```
design_edit_metric_tags.py --tag-length=8 --edit-distance=3 --multiprocessing --processors=72  --output=designtag_8bp_ed3_all.txt


##############################################################################
#  design_edit_metric_tags.py  - generate sequence tags of arbitrary length  #
#                                                                            #
#  Copyright (c) 2009-2011 Brant C. Faircloth                                #
#  621 Charles E. Young Drive                                                #
#  University of California, Los Angeles, 90095, USA                         #
##############################################################################


[Info] Using multiprocessing with 72 cores
[1] Generating all combinations of tags
[2] If selected, removing tags based on filter criteria
[3] There are 65536 tags remaining after filtering
[4] Calculating the Levenshtein distance across the tags
	[Info] There are 132 chunks.
	Processing: ........................................................................
............................................................
Traceback (most recent call last):
  File "/home/langhorst/miniconda3/envs/edittag/bin/design_edit_metric_tags.py", line 500, in <module>
    main()
  File "/home/langhorst/miniconda3/envs/edittag/bin/design_edit_metric_tags.py", line 457, in main
    if distances == None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
